trigger:
  - main

pool:
  - vmImage: ubuntu-latest

steps: 
-task: TerraformTaskV1
inputs:
  provider: 'azurerm'
  command: 'init'
  workingDirectory: sql-server-deploy
  backendServiceArm: 'Pay as you go aiciulian'
