trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'test-Pay-As-You-Go (5667682-6a19-4781-87f8-5c564ec4fec9)'
    ServerName: 'databasedevopspostgresql.database.azure.com'
    SqlUsername: '$(SQL_ADMIN_USERNAME)'
    SqlPassword: '$(SQL_PASSWORD)'
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: 'sql-query/createusers.sql'
    IpDetectionMethod: 'AutoDetect'
